"use client"
// Auto-generated by `npx boneyard-js build` — do not edit
import { registerBones } from 'boneyard-js'
import { configureBoneyard } from 'boneyard-js/react'

import _campaign_create from './campaign-create.bones.json'

configureBoneyard({"color":"#131920","darkColor":"#131920","animate":"shimmer","shimmerColor":"#1e2834","darkShimmerColor":"#1e2834","speed":"2s","shimmerAngle":110,"stagger":80,"transition":300})

registerBones({
  "campaign-create": _campaign_create,
})
